# Generated by Django 5.2.8 on 2025-11-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('firmware', models.CharField(blank=True, max_length=64)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('relay_channel', models.PositiveIntegerField()),
                ('door_type', models.CharField(choices=[('BIG', 'Grande porte'), ('LOCKER', 'Casier')], default='LOCKER', max_length=10)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_enabled', models.BooleanField(default=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='fleur.distributor')),
            ],
            options={
                'unique_together': {('distributor', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('VENDED', 'Vendu'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleur.distributor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleur.slot')),
            ],
        ),
        migrations.CreateModel(
            name='VendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fleur.order')),
            ],
        ),
    ]
