# Generated by Django 5.2.8 on 2025-11-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='home_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
